# Generated by Django 2.0 on 2017-12-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='menulevel',
        ),
    ]
