# Generated by Django 2.0 on 2017-12-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20171219_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
